Classwork & Homework #1
ZalyalovIldar/Lesson1 pull request #1
Opened 2019-09-19 16:19 UTC by EVGKZN

2019-09-19 16:22 UTC, EVGKZN commented
Кузьмин Евгений группа 11-803

2019-09-21 16:14 UTC, ZalyalovIldar requested changes
В целом не плохо 👍  

Исправь в течении 2х дней и будет фулл балл 🥇

2019-09-21 16:14 UTC, ZalyalovIldar commented on ClassWork.playground/Contents.swift
> +class Car{
перед { всегда 1 пробел (поправь для всех мест по коду плз)

2019-09-21 16:14 UTC, ZalyalovIldar commented on ClassWork.playground/Contents.swift
> +    private var plateNumber : Int?
перед двоеточием нет пробела, после есть 1 пробел (поправь для всех мест в обоих файлах плз). 
Это касается всего, где есть двоеточие (классы, переменные, параметры в методах и т.д.)

2019-09-21 16:14 UTC, ZalyalovIldar commented on ClassWork.playground/Contents.swift
> +    override func sound() {
в начале класса ставим 1 пробел (поправь для всех мест плз)

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +        if damage>0{
```swift 
if damage > 0 {

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +            self.health-=damage
self не нужен, 
```swift 
health -= damage

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +var narutorunnerCounter = 15
camelCase -> narutoRunnerCounter

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +    for _ in 1..<guardianCounter {
пробел сверху  и отступы вот так (поправь для остальных мест тоже) 
```Swift 
for _ in 1 ..< guardianCounter {

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +    }
так же можно воспользоваться инициализацией массива через repeat: 
```Swift 
let array = [String](repeating: "repeat", count: 10)
``` 
это создаст массив с 10 одинаковыми объектами, думаю сможешь подстроить под себя ;) 
+ сделай так же для других мест)

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +            narutorunnerCounter += waveCounter*3
```swift
narutorunnerCounter += waveCounter * 3

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +            if guardianArray.count != 0 {
```swift 
!guardianArray.isEmpty

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +            } while guardianArray.count != 0 && attackerArray.count != 0
```swift 
!guardianArray.isEmpty && !attackerArray.isEmpty

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +                            attackerArray.remove(at: attackerArray.firstIndex{$0 === attacker}!)
лучше избегать форса, замени на if let или поставь в условие выше нахождение типа вот так: 
```swift 
if attacker.health <= 0, let attackerToRemove = attackerArray.firstIndex{ $0 === attacker } {
  ...
}
``` 
Это позволит тебе безопасно удалить нужного атакующего, тоже самое можно(читай нужно) провернуть для защитника

2019-09-21 16:14 UTC, ZalyalovIldar commented on HomeWork.playground/Contents.swift
> +    func beginBattle(with attackers: [Unit] = attackersFactory(), guardians: [Unit] = guardiansFactory(), wave: Int = waveCounter) {
в данном случае ок, но на будущее запомни, что задавать вызов метода как дефолтный параметр - не гуд. 
Это как минимум не очевидно)
Желательный вариант был бы оставить обязательные параметры, и в месте вызова метода beginBattle проставить нужное)

2019-09-22 17:16 UTC, ZalyalovIldar commented
🔝

2019-09-22 17:16 UTC, closed without merging