First HW
ZalyalovIldar/Lesson1 pull request #10
Opened 2019-09-24 02:52 UTC by simpleBaga

done

2019-09-24 02:55 UTC, simpleBaga commented
Soshnikov Bogdan

2019-09-24 16:31 UTC, ZalyalovIldar requested changes
ждёмс правок :)

2019-09-24 16:31 UTC, ZalyalovIldar commented on Zone51.playground/Contents.swift
> +    func beginAssault(waves: [Array<Unit>]) {
чтобы сделать массив массивов, достаточно сделать вложенность типа: 
waves: [[Unit]] - так чище выглядит)

2019-09-24 16:31 UTC, ZalyalovIldar commented on Zone51.playground/Contents.swift
> +        if health <= 0{
перед любыми фигурными скобками 1 отступ, поправь везде плиз

2019-09-24 16:31 UTC, ZalyalovIldar commented on Zone51.playground/Contents.swift
> +                            else {break attackerIsAliveCheck}
это конечно сложно читается, но кажется даже оптимизировано малеха. 
Тут оставь, но дальше подобный код не пропущу, стоит разбивать на отдельные методы, и стараться уменьшить кол-во вложенных циклов

2019-09-26 22:01 UTC, simpleBaga commented
[Zone51.playground.zip](https://github.com/ZalyalovIldar/Lesson1/files/3660075/Zone51.playground.zip)

2019-09-27 22:03 UTC, ZalyalovIldar commented
wtf? Кидай коммитом

2019-10-01 11:53 UTC, closed without merging