homework
ZalyalovIldar/Lesson1 pull request #5
Opened 2019-09-23 07:33 UTC by underqcool

2019-09-24 15:51 UTC, ZalyalovIldar requested changes
поправляем, не стесняемся :)

2019-09-24 15:51 UTC, ZalyalovIldar commented on Classwork.playground/Contents.swift
> +    private var name: String
отступ в начале класса (в других местах тоже поправь плиз)

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +        var aliveAttackers = attackers
отступ перед строкой

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +        while aliveGuardians.count != 0 || aliveAttackers.count != 0 {
отступ перед строкой

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +        while aliveGuardians.count != 0 || aliveAttackers.count != 0 {
такие условия проверяем так (поправь в других местах тоже)
```swift 
!aliveGuardians.isEmpty

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +            while (currentAttacker.getHealth()) <= 0 || (currentGuardian.getHealth()) <= 0 {
отступ перед строкой

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +                if currentAttacker.getHealth() <= 0{
отступ перед строкой

2019-09-24 15:51 UTC, ZalyalovIldar commented on Game.playground/Contents.swift
> +            if isAttackerLoser == true {
достаточно проверять саму переменную, не сравнивая с true/false
```swift 
if isAttackerLoser { ... } -> если true 
if !isAttackerLoser { ... } -> если false

2019-09-27 21:54 UTC, ZalyalovIldar commented
Имя?

2019-09-27 21:56 UTC, underqcool commented
Мялицин Максим

On Sat, Sep 28, 2019, 00:54 Ildar Zalyalov <notifications@github.com> wrote:

> Имя?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ZalyalovIldar/Lesson1/pull/5?email_source=notifications&email_token=ALK6ZRFF6B6OFDLJ5QF2MDLQLZ6K5A5CNFSM4IZHKGD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72F5EI#issuecomment-536108689>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALK6ZRCDZTPXVLYAXKZ77MLQLZ6K5ANCNFSM4IZHKGDQ>
> .
>

2019-09-27 21:58 UTC, ZalyalovIldar commented
:ok

2019-09-27 21:58 UTC, closed without merging