added hm
ZalyalovIldar/Lesson1 pull request #6
Opened 2019-09-23 09:08 UTC by Sartan322

2019-09-24 12:50 UTC, Sartan322 commented
Prokopev Pavel 11-807

2019-09-24 16:05 UTC, ZalyalovIldar requested changes
поржал с классов, давай правки и апрув)

2019-09-24 16:05 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +    func specialAbility() -> Int {
отступ перед строкой (между функциями 1 отступ) - поправь для остальных случаев тоже плиз

2019-09-24 16:05 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +        if(health<1) {
```swift 
if (health < 1)

2019-09-24 16:05 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +        self.health += 15
без self

2019-09-24 16:05 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +        if Int.random(in: 1...2)>1 {
```swift 
Int.random(in: 1...2) > 1

2019-09-24 16:05 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +    var SPECIAL: [Int]
только camelCase, никаких капсов)

2019-09-27 21:55 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +    var sPECIAL: [Int]
лол, почему не просто special?)

2019-09-27 21:56 UTC, ZalyalovIldar commented on 51Zone.playground/Contents.swift
> +        print("Р РёРєР°СЂРґРѕ РЅР°С‡РёРЅР°РµС‚ С„Р»РµРєСЃРёС‚СЊ СЃРѕС‚СЂСЏСЃР°СЏ Р·РµРјР»СЋ РїРѕРґ РІСЂР°РіР°РјРё")
втф? с текстом?

2019-10-01 11:52 UTC, closed without merging