Homework
ZalyalovIldar/Lesson1 pull request #9
Opened 2019-09-23 16:58 UTC by Destosed

Лужбин Никита 11-811

2019-09-24 16:23 UTC, ZalyalovIldar requested changes
"еще один фан Jojo обнаружен" 
немного правок и апрув 🔝

2019-09-24 16:23 UTC, ZalyalovIldar commented on Zone51.playground/Contents.swift
> +                let attacker = currentAttacker as! Ricardo
сделать все такие if-ы через if let, чтобы без лишней работы) 
``` swift 
if let ricardoBoy = currentAttacker as? Ricardo { }

2019-09-24 16:23 UTC, ZalyalovIldar commented on Zone51.playground/Contents.swift
>              var currentDefender = defendersInBattle.randomElement()!
избавиться от форсов, через if let или как то по другому :)

2019-09-24 17:50 UTC, Destosed commented on Zone51.playground/Contents.swift
>              var currentDefender = defendersInBattle.randomElement()!
А это точно нужно? У меня же в while условие 

> while !attackersInBattle.isEmpty && !defendersInBattle.isEmpty

2019-09-27 22:02 UTC, ZalyalovIldar commented
🆗

2019-09-27 22:02 UTC, closed without merging